### ISSUE TITLE
Inserted image cannot be read by Typst compiler unless the App is restarted.

### ISSUE THREAD

**Issue by Qubik65536** [iXORTech/Typstify#1]
When an image is inserted, even the image is added to the project bundle, it is actually not written to the file directory until the next auto save is triggered by the OS.

This prevents the Typst compiler from reading the image and render the document having the image included.

Related: https://github.com/mchakravarty/ProjectNavigator/issues/27#issuecomment-2282200608

**Comment by Pe-chi** [comment]
I made a pull request (#6) to fix this issue.
